/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'chan5120' at '12/29/14 1:19 PM' with Gradle 2.2.1
 *
 * @author chan5120, @date 12/29/14 1:19 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
