/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'chan5120' at '12/29/14 1:19 PM' with Gradle 2.2.1
 *
 * @author chan5120, @date 12/29/14 1:19 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
